services:
  user_db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - user_db:/data/db

  user_db_adapter:
    build: ./adapter/user_db
    restart: always
    environment:
      - DB_HOST=user_db
    ports:
      - 3000:3000

volumes:
  user_db:
